module.exports = function (gatewayExpressApp) {

 gatewayExpressApp.get('/token', (req, res) => {
    try{
              let secret = null;
              secret = '6UTcjMGZ3785URu4JgzNbb' ; // this is the keySecret generated by eg credential create
              let token = jwt.sign( {
                  "sub": "6QuT3rJ8d43w4mdW6PGlAg", //keyId generated by eg create
                  "name": "BERI Prelogin"
                },secret);
              console.log('TOKEN: ' + token);
              
              
              //verifying JWT token.
              //let decoded = jwt.verify(token ,'privateKey'); //Decoding JWT using keySecret 
              //console.dir(decoded, { depth : null ,colors : true});

              res.json({
                jwt: token
              });
    } catch(e){
              logger.error(`Generate JWT error with ${e}`);
              res.status(500).json(`There is something wrong with server: ${e}`);
    }
  });

};